### ISSUE TITLE
Getting a build error for Android with PhoneGap

### ISSUE THREAD

**Issue by W1ldW1ngs** [phfsantos/cordova-plugin-smaato#14]
Anyone else getting a build error for Android with this plugin?

Any insight @phfsantos ?

Build Log:

` Build Date: 2017-08-16 17:02:31 +0000
Subproject Path: CordovaLib
Configuration on demand is an incubating feature.
Incremental java compilation is an incubating feature.
:preBuild UP-TO-DATE
:preReleaseBuild UP-TO-DATE
:checkReleaseManifest
:preDebugBuild UP-TO-DATE
:CordovaLib:preBuild UP-TO-DATE
:CordovaLib:preDebugBuild UP-TO-DATE
:CordovaLib:checkDebugManifest
:CordovaLib:prepareDebugDependencies
:CordovaLib:compileDebugAidl
:CordovaLib:compileDebugNdk UP-TO-DATE
:CordovaLib:compileLint
:CordovaLib:copyDebugLint UP-TO-DATE
:CordovaLib:mergeDebugShaders
:CordovaLib:compileDebugShaders
:CordovaLib:generateDebugAssets
:CordovaLib:mergeDebugAssets
:CordovaLib:mergeDebugProguardFiles
:CordovaLib:packageDebugRenderscript UP-TO-DATE
:CordovaLib:compileDebugRenderscript
:CordovaLib:generateDebugResValues
:CordovaLib:generateDebugResources
:CordovaLib:packageDebugResources
:CordovaLib:processDebugManifest
:CordovaLib:generateDebugBuildConfig
:CordovaLib:processDebugResources
:CordovaLib:generateDebugSources
:CordovaLib:incrementalDebugJavaCompilationSafeguard
:CordovaLib:compileDebugJavaWithJavac
:CordovaLib:compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
:CordovaLib:processDebugJavaRes UP-TO-DATE
:CordovaLib:transformResourcesWithMergeJavaResForDebug
:CordovaLib:transformClassesAndResourcesWithSyncLibJarsForDebug
:CordovaLib:mergeDebugJniLibFolders
:CordovaLib:transformNative_libsWithMergeJniLibsForDebug
:CordovaLib:transformNative_libsWithSyncJniLibsForDebug
:CordovaLib:bundleDebug
:CordovaLib:preReleaseBuild UP-TO-DATE
:CordovaLib:checkReleaseManifest
:CordovaLib:prepareReleaseDependencies
:CordovaLib:compileReleaseAidl
:CordovaLib:compileReleaseNdk UP-TO-DATE
:CordovaLib:copyReleaseLint UP-TO-DATE
:CordovaLib:mergeReleaseShaders
:CordovaLib:compileReleaseShaders
:CordovaLib:generateReleaseAssets
:CordovaLib:mergeReleaseAssets
:CordovaLib:mergeReleaseProguardFiles
:CordovaLib:packageReleaseRenderscript UP-TO-DATE
:CordovaLib:compileReleaseRenderscript
:CordovaLib:generateReleaseResValues
:CordovaLib:generateReleaseResources
:CordovaLib:packageReleaseResources
:CordovaLib:processReleaseManifest
:CordovaLib:generateReleaseBuildConfig
:CordovaLib:processReleaseResources
:CordovaLib:generateReleaseSources
:CordovaLib:incrementalReleaseJavaCompilationSafeguard
:CordovaLib:compileReleaseJavaWithJavac
:CordovaLib:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
:CordovaLib:processReleaseJavaRes UP-TO-DATE
:CordovaLib:transformResourcesWithMergeJavaResForRelease
:CordovaLib:transformClassesAndResourcesWithSyncLibJarsForRelease
:CordovaLib:mergeReleaseJniLibFolders
:CordovaLib:transformNative_libsWithMergeJniLibsForRelease
:CordovaLib:transformNative_libsWithSyncJniLibsForRelease
:CordovaLib:bundleRelease
:prepareComAndroidSupportAnimatedVectorDrawable2531Library
:prepareComAndroidSupportAppcompatV72531Library
:prepareComAndroidSupportCardviewV72531Library
:prepareComAndroidSupportCustomtabs2531Library
:prepareComAndroidSupportSupportCompat2531Library
:prepareComAndroidSupportSupportCoreUi2531Library
:prepareComAndroidSupportSupportCoreUtils2531Library
:prepareComAndroidSupportSupportFragment2531Library
:prepareComAndroidSupportSupportMediaCompat2531Library
:prepareComAndroidSupportSupportV132340Library
:prepareComAndroidSupportSupportV42531Library
:prepareComAndroidSupportSupportVectorDrawable2531Library
:prepareComFacebookAndroidFacebookAndroidSdk4250Library
:prepareComGoogleAndroidGmsPlayServicesAds830Library
:prepareComGoogleAndroidGmsPlayServicesAnalytics1102Library
:prepareComGoogleAndroidGmsPlayServicesAnalyticsImpl1102Library
:prepareComGoogleAndroidGmsPlayServicesBase1102Library
:prepareComGoogleAndroidGmsPlayServicesBasement1102Library
:prepareComGoogleAndroidGmsPlayServicesGcm1102Library
:prepareComGoogleAndroidGmsPlayServicesIid1102Library
:prepareComGoogleAndroidGmsPlayServicesTagmanagerV4Impl1102Library
:prepareComGoogleAndroidGmsPlayServicesTasks1102Library
:prepareMeLeolinShortcutBadger1114Library
:prepareProjectCordovaLibUnspecifiedReleaseLibrary
:prepareReleaseDependencies
:compileReleaseAidl
:compileReleaseRenderscript
:generateReleaseBuildConfig
:generateReleaseResValues
:generateReleaseResources
:mergeReleaseResources
:processReleaseManifest
:processReleaseResourceswarning: string 'com_facebook_loginview_log_in_button_continue_f1gender' has no default translation.
warning: string 'com_facebook_loginview_log_in_button_continue_m2gender' has no default translation.
warning: string 'com_facebook_loginview_log_out_action_f1gender' has no default translation.
warning: string 'com_facebook_loginview_log_out_action_m2gender' has no default translation.
warning: string 'com_facebook_loginview_log_out_button_f1gender' has no default translation.
warning: string 'com_facebook_loginview_log_out_button_m2gender' has no default translation.
warning: string 'com_facebook_loginview_logged_in_as_f1gender' has no default translation.
warning: string 'com_facebook_loginview_logged_in_as_m2gender' has no default translation.
warning: string 'com_facebook_loginview_logged_in_using_facebook_f1gender' has no default translation.
warning: string 'com_facebook_loginview_logged_in_using_facebook_m2gender' has no default translation.
warning: string 'com_facebook_send_button_text_f1gender' has no default translation.
warning: string 'com_facebook_send_button_text_m2gender' has no default translation.
warning: string 'com_facebook_share_button_text_f1gender' has no default translation.
warning: string 'com_facebook_share_button_text_m2gender' has no default translation.
warning: string 'com_facebook_smart_login_confirmation_cancel_f1gender' has no default translation.
warning: string 'com_facebook_smart_login_confirmation_cancel_m2gender' has no default translation.
warning: string 'com_facebook_smart_login_confirmation_continue_as_f1gender' has no default translation.
warning: string 'com_facebook_smart_login_confirmation_continue_as_m2gender' has no default translation.
warning: string 'com_facebook_smart_login_confirmation_title_f1gender' has no default translation.
warning: string 'com_facebook_smart_login_confirmation_title_m2gender' has no default translation.
warning: string 'com_facebook_tooltip_default_f1gender' has no default translation.
warning: string 'com_facebook_tooltip_default_m2gender' has no default translation.

:generateReleaseSources
:incrementalReleaseJavaCompilationSafeguard
:compileReleaseJavaWithJavac
:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
:compileReleaseNdk UP-TO-DATE
:compileReleaseSources
:mergeReleaseShaders
:compileReleaseShaders
:generateReleaseAssets
:mergeReleaseAssets
:transformClassesWithDexForRelease FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformClassesWithDexForRelease'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/internal/zzbf;

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 10.19 secs
Error: /project/gradlew: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
warning: string 'com_facebook_loginview_log_in_button_continue_f1gender' has no default translation.
warning: string 'com_facebook_loginview_log_in_button_continue_m2gender' has no default translation.
warning: string 'com_facebook_loginview_log_out_action_f1gender' has no default translation.
warning: string 'com_facebook_loginview_log_out_action_m2gender' has no default translation.
warning: string 'com_facebook_loginview_log_out_button_f1gender' has no default translation.
warning: string 'com_facebook_loginview_log_out_button_m2gender' has no default translation.
warning: string 'com_facebook_loginview_logged_in_as_f1gender' has no default translation.
warning: string 'com_facebook_loginview_logged_in_as_m2gender' has no default translation.
warning: string 'com_facebook_loginview_logged_in_using_facebook_f1gender' has no default translation.
warning: string 'com_facebook_loginview_logged_in_using_facebook_m2gender' has no default translation.
warning: string 'com_facebook_send_button_text_f1gender' has no default translation.
warning: string 'com_facebook_send_button_text_m2gender' has no default translation.
warning: string 'com_facebook_share_button_text_f1gender' has no default translation.
warning: string 'com_facebook_share_button_text_m2gender' has no default translation.
warning: string 'com_facebook_smart_login_confirmation_cancel_f1gender' has no default translation.
warning: string 'com_facebook_smart_login_confirmation_cancel_m2gender' has no default translation.
warning: string 'com_facebook_smart_login_confirmation_continue_as_f1gender' has no default translation.
warning: string 'com_facebook_smart_login_confirmation_continue_as_m2gender' has no default translation.
warning: string 'com_facebook_smart_login_confirmation_title_f1gender' has no default translation.
warning: string 'com_facebook_smart_login_confirmation_title_m2gender' has no default translation.
warning: string 'com_facebook_tooltip_default_f1gender' has no default translation.
warning: string 'com_facebook_tooltip_default_m2gender' has no default translation.

Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformClassesWithDexForRelease'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/internal/zzbf;

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
    at ChildProcess.whenDone (/project/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5) `

**Comment by W1ldW1ngs** [comment]
Was able to get further with this by installing a MultiDex plugin however then I ran into dependency issues.
See Here:

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformClassesWithJarMergingForRelease'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: com/google/android/gms/internal/zzbp.class


Some forums have suggested using gradle dependencies? 
https://github.com/phonegap/build/issues/507
