### ISSUE TITLE
googleplayservices

### ISSUE THREAD

**Issue by ghost** [phfsantos/cordova-plugin-smaato#7]
Hello there, hope you are all doing well.
I'm having a problem while I try to install the plugin smaato, here is the npm error:

```
$ cordova plugin add cordova-plugin-smaato
Fetching plugin "cordova-plugin-smaato" via npm
Installing "cordova-plugin-smaato" for android
Notice: com.google.playservices@19.0.0 has been automatically converted to cordova-plugin-googleplayservices and fetched from npm. This is due to our old plugins registry shutting down.
Fetching plugin "cordova-plugin-googleplayservices@19.0.0" via npm
Failed to install 'cordova-plugin-smaato':CordovaError: Failed to fetch plugin cordova-plugin-googleplayservices@19.0.0 via registry.

Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: version not found: cordova-plugin-googleplayservices@19.0.0
    at c:\Users\Cedrik\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\fetch.js:146:33
    at _rejected (c:\Users\Cedrik\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:797:24)
    at c:\Users\Cedrik\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:823:30
    at Promise.when (c:\Users\Cedrik\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:1035:31)
    at Promise.promise.promiseDispatch (c:\Users\Cedrik\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:741:41)
    at c:\Users\Cedrik\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:557:44
    at flush (c:\Users\Cedrik\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:108:17)
    at doNTCallback0 (node.js:408:9)
    at process._tickCallback (node.js:337:13)
Error: Failed to fetch plugin cordova-plugin-googleplayservices@19.0.0 via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: version not found: cordova-plugin-googleplayservices@19.0.0
```

**Comment by phfsantos** [comment]
I have a fix for that already. I will commit it soon. Thanks

**Comment by syanwar** [comment]
sorry, is there any progress?

**Comment by rafaelcoutinho** [comment]
Having the same issue

**Comment by phfsantos** [comment]
It should be fixed
